language: node_js
before_script:
  - npm install -g npm

node_js:
  - "8"

os: osx
notifications:
  slack: tbdsillysailingpun:qq46CINpRzpkYPRbpRATa2xK
    on_success: always

matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: osx
      node_js: "8"
      install: true
      script: npm i && npm run tslint
    - stage: "Build"
      os: osx
      env: 
        - BuildiOS="12"
        - Xcode="10.0"
      osx_image: xcode10
      language: node_js 
      node_js: "8"
      
      script:
        - tns build ios --bundle 
