language: node_js
before_script:
  - npm install -g npm
  - npm ci 

node_js:
  - "8"

os: osx
notifications:
  slack: tbdsillysailingpun:qq46CINpRzpkYPRbpRATa2xK


matrix:
  include:
    - stage: "Build"
      os: osx
      env: 
        - BuildiOS="12"
        - Xcode="10.0"
      osx_image: xcode10
      language: node_js 
      node_js: "8"
      
script: tns build ios --bundle 
