language: node_js
before_script:
  - npm install -g npm
  - npm install nativescript
node_js:
  - "8"

# os: osx
# notifications:
#   slack: tbdsillysailingpun:qq46CINpRzpkYPRbpRATa2xK


matrix:
  include:
    - stage: "Build"
      os: osx
      language: node_js 
      node_js: "8"
      
script: tns build ios --bundle 
